#!/bin/bash
# shellcheck disable=SC2015

########
#
# Copyright © 2021 @RubenKelevra
#
# LICENSE contains the licensing informations
#
########

# ipfs-mfs folder
ipfs_folder='endeavouros.pkg.pacman.store'

# rsync url
rsync_source='rsync://mirror.erickochen.nl/endeavouros/'

# http/https url to the lastupdate file on the same server, to skip unnecessary rsync syncs
lastupdate_url='https://mirror.erickochen.nl/endeavouros/synctrace.txt'
